### ISSUE TITLE
Need package with >1 version, all deps & devDeps available in mock-registry

### ISSUE THREAD

**Issue by smikes** [npm/npm-registry-mock#29]
To properly test `npm install <pkg>` when the package has a listed version in `devDependencies`, I am running `npm install --dev checker`. This fails when `npm` tries to (properly) install all the devDependencies of `checker`, because `mocha` is not in the mock registry.

I propose adding a new mock module that has no dependencies or devDependencies, and has several valid versions, for testing install/update semver behavior.

versions would be: 
"0.0.0", "0.0.1", "0.0.2", "0.1.0", "0.1.1", "0.1.2", "0.2.0", "0.2.1", "0.2.2"
"1.0.0", "1.0.1", "1.0.2", "1.1.0", "1.1.1", "1.1.2", "1.2.0", "1.2.1", "1.2.2",
"2.0.0", "2.0.1", "2.0.2", "2.1.0", "2.1.1", "2.1.2", "2.2.0", "2.2.1", "2.2.2"

dist-tags `latest` on 2.2.2, `legacy` on "1.2.2"

Any objections/suggestions/corrections?  Maybe there is a simpler way to test this that am overlooking?

Ref https://github.com/npm/npm/pull/7313 , the test case where I ran into the `mocha` thing.

**Comment by robertkowalski** [comment]
sounds good!

**Comment by iarna** [comment]
Our approach now is more often to create the test-specific mock in the test, rather than farming it out over here. The referenced issue is quite old and closed so I'm just going to close this too.
